### PR TITLE
Add invalid_scope error message

### PR DESCRIPTION
**Pull request by FlaShG**
The `invalid_scope` error message is either thrown when the given scope is incorrect (as in: not `appstore::apps:readwrite`) or, as it turns out, if the security profile that is used is not attached to the App Submission API. This error message makes the plugin more verbose about that mistake.

Also some automated code cleanups.

### CODE REVIEW

**Comment by tmm1** [comment]
👍

**Comment by mohammedhemaid** [comment]
@FlaShG can you please check these conflicts and try to resolve them if possible

**Comment by FlaShG** [comment]
Seems to only have been some indentation - should be fine now.

**Comment by mohammedhemaid** [comment]
@FlaShG I see the file changes is 0, and I noticed that we already merged this before and have it in the last release
So now we have a stable version 0.4.0 and you can start using it

**Pull request merged**
